Repository dnd-side-project/dnd-12th-1-iOS, pull requests merged in 2025-02, with the labels that each got.

#9 Network layer를 구현했어요
  dogether.xcodeproj/project.pbxproj
  dogether.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  dogether/Data/Model/CreateGroupRequest.swift
  dogether/Data/Model/CreateGroupResponse.swift
  dogether/Data/Network/NetworkEndpoint.swift
  dogether/Data/Network/NetworkError.swift
  dogether/Data/Network/NetworkManager.swift
  dogether/Data/Network/NetworkService.swift
  dogether/Data/Network/ServerResponse.swift
  dogether/TestViewController.swift
Labels: feat

#13 PR Template을 Issue에서 삭제했어요
  .github/ISSUE_TEMPLATE/pr-template.md
Labels: docs

#12 PR Template 재생성했어요
  .github/PRTemplate
Labels: docs

#18 PR Template 파일명 수정했습니다
  .github/PULL_REQUEST_TEMPLATE
Labels: docs

#14 NetworkLayer를 구현했어요
  dogether/Data/Model/CreateGroupRequest.swift
  dogether/Data/Model/DogetherCodes.swift
  dogether/Data/Model/HTTPStatusErrors.swift
  dogether/Data/Model/RankingModel.swift
  dogether/Data/Model/ReviewModel.swift
  dogether/Data/Network/NetworkEndpoint.swift
  dogether/Data/Network/NetworkManager.swift
  dogether/Data/Network/NetworkService.swift
  dogether/Data/Network/Request/AppleLoginRequest.swift
  dogether/Data/Network/Request/CertifyTodoRequest.swift
  dogether/Data/Network/Request/CreateGroupRequest.swift
  dogether/Data/Network/Request/CreateTodosRequest.swift
  dogether/Data/Network/Request/JoinGroupRequest.swift
  dogether/Data/Network/Request/RemoveNotiTokenRequest.swift
  dogether/Data/Network/Request/ReviewTodoRequest.swift
  dogether/Data/Network/Request/SaveNotiTokenRequest.swift
  dogether/Data/Network/Request/WithdrawRequest.swift
  dogether/Data/Network/Response/AppleLoginResponse.swift
  dogether/Data/Network/Response/CreateGroupResponse.swift
  dogether/Data/Network/Response/GetGroupInfoResponse.swift
  dogether/Data/Network/Response/GetMySummaryResponse.swift
  dogether/Data/Network/Response/GetMyYesterdayTodosResponse.swift
  dogether/Data/Network/Response/GetReviewResponse.swift
  dogether/Data/Network/Response/GetReviewsResponse.swift
  dogether/Data/Network/Response/GetTeamSummaryResponse.swift
  dogether/Data/Network/Router/AuthRouter.swift
  dogether/Data/Network/Router/GroupsRouter.swift
  dogether/Data/Network/Router/NotificationsRouter.swift
  dogether/Data/Network/Router/TodoCertificationsRouter.swift
  dogether/Data/Network/Router/TodosRouter.swift
  dogether/Data/Network/ServerResponse.swift
  dogether/Data/Protocol/GroupInfo.swift
  dogether/Data/Protocol/JoinCode.swift
  dogether/Data/Protocol/ReviewInfo.swift
  dogether/Data/Protocol/Todos.swift
  dogether/Data/Protocol/TokenInfo.swift
  dogether/Data/Protocol/TotalCount.swift
  dogether/TestViewController.swift
Labels: chore

#21 수출 규정 관련 문서 위치를 수정했어요
  dogether/Info.plist
Labels: docs

#16 폴더링을 수정했어요
  dogether.xcodeproj/project.pbxproj
  dogether.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  dogether/App/AppDelegate.swift
  dogether/App/SceneDelegate.swift
  dogether/Assets.xcassets/logo.imageset/Contents.json
  dogether/Assets.xcassets/logo.imageset/logo.png
  dogether/Base.lproj/LaunchScreen.storyboard
  dogether/Base.lproj/Main.storyboard
  dogether/Config/Info.plist
  dogether/Data/DataSources/TodoDataSource.swift
  dogether/Data/Repositories/TodoRepository.swift
  dogether/Domain/Entity/User.swift
  dogether/Domain/Interface/TodoRepositoryInterface.swift
  dogether/Domain/UseCases/AppleSignInDelegate.swift
  dogether/Domain/UseCases/DeleteTodoUseCase.swift
  dogether/Presentation/Common/BaseViewController.swift
  dogether/Presentation/Common/PrimaryButton.swift
  dogether/Presentation/View/LoginViewController.swift
  dogether/Presentation/View/ViewController.swift
  dogether/Presentation/ViewModel/TodoListViewModel.swift
  dogether/Resource/Assets/Assets.xcassets/AppIcon.appiconset/Contents.json
  dogether/Test/UnitTest/TodoRepositoryTest.swift
  dogether/Utility/Extension/DateExt.swift
  dogether/Utility/Manager/UserDefaultsManager.swift
  dogether/Utility/Network/APIManager.swift
Labels: chore

#23 공용 컴포넌트를 추가했어요, Assets & Resource쪽 수정 사항을 반영했어요
  dogether.xcodeproj/project.pbxproj
  dogether.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  dogether/Presentation/Common/DogetherButton.swift
  dogether/Presentation/Common/DogetherHeader.swift
  dogether/Resource/Assets/Assets.xcassets/Icon/logo.imageset/Contents.json
  dogether/Resource/Assets/Assets.xcassets/Icon/logo.imageset/logo.png
  dogether/Resource/Assets/Assets.xcassets/Icon/logo_typo.imageset/Contents.json
  dogether/Resource/Assets/Assets.xcassets/Icon/logo_typo.imageset/logo_typo.png
  dogether/Resource/Colors.swift
  dogether/Resource/Fonts.swift
  dogether/Resource/Icons.swift
Labels: feat, refactor

#27 첫 진입 화면과 그룹 생성 화면, 완료 화면을 구현했어요
  dogether/Data/Network/Request/CreateGroupRequest.swift
  dogether/Data/Network/Request/ReviewTodoRequest.swift
  dogether/Domain/Entity/CompleteTypes.swift
  dogether/Domain/Entity/CreateGroupSteps.swift
  dogether/Domain/Entity/Directions.swift
  dogether/Domain/Entity/GroupChallengeDurations.swift
  dogether/Domain/Entity/GroupStartAts.swift
  dogether/Domain/Entity/ReviewResults.swift
  dogether/Presentation/Common/BaseViewController.swift
  dogether/Presentation/Common/DogetherButton.swift
  dogether/Presentation/Common/DogetherCountView.swift
  dogether/Presentation/Common/DogetherGroupInfo.swift
  dogether/Presentation/Common/DogetherHeader.swift
  dogether/Presentation/Common/NavigationHeader.swift
  dogether/Presentation/View/CompleteViewController.swift
  dogether/Presentation/View/CreateGroupViewController.swift
  dogether/Presentation/View/StartViewController.swift
  dogether/Presentation/ViewModel/CreateGroupViewModel.swift
  dogether/Resource/Assets/Assets.xcassets/Color/Point/Point-Red.colorset/Contents.json
  dogether/Resource/Assets/Assets.xcassets/Icon/copy.imageset/Contents.json
  dogether/Resource/Assets/Assets.xcassets/Icon/copy.imageset/copy.png
  dogether/Resource/Assets/Assets.xcassets/Icon/minus-button.imageset/Contents.json
  dogether/Resource/Assets/Assets.xcassets/Icon/minus-button.imageset/minus-button.png
  dogether/Resource/Assets/Assets.xcassets/Icon/plus-button.imageset/Contents.json
  dogether/Resource/Assets/Assets.xcassets/Icon/plus-button.imageset/plus-button.png
  dogether/Resource/Assets/Assets.xcassets/Icon/share.imageset/Contents.json
  dogether/Resource/Assets/Assets.xcassets/Icon/share.imageset/share.png
  dogether/Resource/Fonts.swift
  dogether/Utility/Manager/DateFormatterManager.swift
Labels: feat, design

#29 애플 로그인 화면 구현했어요
  dogether.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  dogether/Domain/UseCases/AppleSignInDelegate.swift
  dogether/Presentation/View/LoginSuccessViewController.swift
  dogether/Presentation/View/LoginViewController.swift
  dogether/Presentation/View/ViewController.swift
  dogether/Presentation/ViewModel/LoginViewModel.swift
  dogether/Presentation/ViewModel/TodoListViewModel.swift
  dogether/Utility/Manager/UserDefaultsManager.swift
Labels: feat

#37 온보딩 화면 구현했어요
  dogether/App/SceneDelegate.swift
  dogether/Config/Info.plist
  dogether/Presentation/View/LoginSuccessViewController.swift
  dogether/Presentation/View/LoginViewController.swift
  dogether/Presentation/View/OnboardingViewController.swift
Labels: feat

#40 메인 화면을 구현했어요
  dogether/Domain/Entity/FilterTypes.swift
  dogether/Domain/Entity/MainViewStatus.swift
  dogether/Domain/Entity/SheetStatus.swift
  dogether/Domain/Entity/TodoInfo.swift
  dogether/Domain/Entity/TodoStatus.swift
  dogether/Presentation/Common/DogetherTodoItem.swift
  dogether/Presentation/View/MainViewController.swift
  dogether/Presentation/ViewModel/MainViewModel.swift
  dogether/Resource/Assets/Assets.xcassets/Icon/Status/reject.imageset/Contents.json
  dogether/Resource/Assets/Assets.xcassets/Icon/Status/reject.imageset/denied.png
  dogether/Utility/Manager/DateFormatterManager.swift
Labels: feat, design

#41 순위 화면을 구현했어요
  dogether/Presentation/Common/RankingTopView.swift
  dogether/Presentation/Common/RankingView.swift
  dogether/Presentation/View/RankingViewController.swift
  dogether/Presentation/ViewModel/RankingViewModel.swift
  dogether/Resource/Assets/Assets.xcassets/Icon/Status/certification.imageset/Contents.json
  dogether/Resource/Assets/Assets.xcassets/Icon/Status/certification.imageset/badge.png
  dogether/Resource/Assets/Assets.xcassets/Icon/profile/Contents.json
  dogether/Resource/Assets/Assets.xcassets/Icon/profile/profile1.imageset/Contents.json
  dogether/Resource/Assets/Assets.xcassets/Icon/profile/profile1.imageset/profile1.png
  dogether/Resource/Assets/Assets.xcassets/Icon/profile/profile2.imageset/Contents.json
  dogether/Resource/Assets/Assets.xcassets/Icon/profile/profile2.imageset/profileExample.png
  dogether/Resource/Assets/Assets.xcassets/Icon/profile/profile3.imageset/Contents.json
  dogether/Resource/Assets/Assets.xcassets/Icon/profile/profile3.imageset/profile3.png
  dogether/Resource/Assets/Assets.xcassets/Icon/profile/profile4.imageset/Contents.json
  dogether/Resource/Assets/Assets.xcassets/Icon/profile/profile4.imageset/profile4.png
Labels: feat, design

#43 NavigationManager를 구현했어요
  dogether/App/AppDelegate.swift
  dogether/App/SceneDelegate.swift
  dogether/Data/Network/NetworkEndpoint.swift
  dogether/Domain/Entity/ButtonStatus.swift
  dogether/Presentation/Common/DogetherButton.swift
  dogether/Presentation/Common/NavigationHeader.swift
  dogether/Presentation/View/CompleteViewController.swift
  dogether/Presentation/View/GroupCreateViewController.swift
  dogether/Presentation/View/GroupJoinViewController.swift
  dogether/Presentation/View/LoginSuccessViewController.swift
  dogether/Presentation/View/MainViewController.swift
  dogether/Presentation/View/OnboardingViewController.swift
  dogether/Presentation/View/SplashViewController.swift
  dogether/Presentation/View/StartViewController.swift
  dogether/Presentation/ViewModel/GroupCreateViewModel.swift
  dogether/Resource/Assets/Assets.xcassets/Icon/Logo/logo.imageset/logo.png
  dogether/Resource/Assets/Assets.xcassets/Icon/Logo/logo_typo.imageset/logo_typo.png
  dogether/Utility/Extension/AppDelegateExt.swift
  dogether/Utility/Extension/DateExt.swift
  dogether/Utility/Manager/NavigationManager.swift
Labels: feat, chore, design

#44 투두 작성 화면을 구현했어요
  dogether/App/SceneDelegate.swift
  dogether/Data/Protocol/Identifier.swift
  dogether/Presentation/Cell/ToDoTableViewCell.swift
  dogether/Presentation/Common/BaseTableViewCell.swift
  dogether/Presentation/View/TodoWriteViewController.swift
  dogether/Utility/Manager/DateFormatterManager.swift
Labels: feat, design

#48 투두 검사 화면을 구현했어요
  dogether/Domain/Entity/PopupTypes.swift
  dogether/Presentation/Common/CertificationPopupView.swift
  dogether/Presentation/Common/ExaminationModalityView.swift
  dogether/Presentation/Common/RejectReasonPopupView.swift
  dogether/Presentation/View/ModalityViewController.swift
  dogether/Presentation/View/PopupViewController.swift
  dogether/Utility/Manager/ModalityManager.swift
  dogether/Utility/Manager/PopupManager.swift
Labels: feat, chore, design

#49 온보딩 화면을 구현했어요
  dogether/Presentation/View/OnboardingViewController.swift
  dogether/Resource/Assets/Assets.xcassets/Icon/Status/onboarding1.imageset/Contents.json
  dogether/Resource/Assets/Assets.xcassets/Icon/Status/onboarding1.imageset/onboarding1.png
  dogether/Resource/Assets/Assets.xcassets/Icon/Status/onboarding2.imageset/Contents.json
  dogether/Resource/Assets/Assets.xcassets/Icon/Status/onboarding2.imageset/onboarding2.png
  dogether/Resource/Assets/Assets.xcassets/Icon/Status/onboarding3.imageset/Contents.json
  dogether/Resource/Assets/Assets.xcassets/Icon/Status/onboarding3.imageset/onboarding3.png
Labels: feat, design

#50 투두작성 화면을 구현했어요
  dogether/Presentation/Cell/ToDoWriteListTableViewCell.swift
  dogether/Presentation/Common/BaseView.swift
  dogether/Presentation/View/TodoWriteViewController.swift
Labels: feat, design

#51 마이페이지 화면을 구현했어요
  dogether/Presentation/Common/AlertHelper.swift
  dogether/Presentation/View/MyPageViewController.swift
Labels: feat, design

#57 담당 화면 이슈를 수정했어요
  dogether/Presentation/View/GroupJoinViewController.swift
  dogether/Presentation/View/MyPageViewController.swift
  dogether/Presentation/View/TodoWriteViewController.swift
  dogether/Resource/Assets/Assets.xcassets/Icon/Status/onboarding1.imageset/Contents.json
  dogether/Resource/Assets/Assets.xcassets/Icon/Status/onboarding1.imageset/onboarding1-2.png
  dogether/Resource/Assets/Assets.xcassets/Icon/Status/onboarding1.imageset/onboarding1.png
  dogether/Resource/Assets/Assets.xcassets/Icon/Status/onboarding2.imageset/Contents.json
  dogether/Resource/Assets/Assets.xcassets/Icon/Status/onboarding2.imageset/onboarding2-2.png
  dogether/Resource/Assets/Assets.xcassets/Icon/Status/onboarding2.imageset/onboarding2.png
  dogether/Resource/Assets/Assets.xcassets/Icon/Status/onboarding3.imageset/Contents.json
  dogether/Resource/Assets/Assets.xcassets/Icon/Status/onboarding3.imageset/onboarding3-2.png
  dogether/Resource/Assets/Assets.xcassets/Icon/Status/onboarding3.imageset/onboarding3.png
Labels: chore, fix
